### ISSUE TITLE
🛠️ [refactor] 타입스크립트 migration

### ISSUE THREAD

**Issue by developomp** [binary-ho/imhere-client#12]
# 🛠️ 리팩토링이 필요한 부분

매우 타입!

![image](https://user-images.githubusercontent.com/40858122/234758462-fdc14f50-798d-4c0c-83ff-6b3783117fe5.png)

타입스크립트 = 기가채드

![image](https://user-images.githubusercontent.com/40858122/234758470-9b40135f-606d-4655-afca-ffb20be68a79.png)

자바스크립트 나빠요

![image](https://user-images.githubusercontent.com/40858122/234758476-4f8a3353-2e04-4432-99c4-bf67d63ae6fc.png)

이상입니다.

# 리팩토링 작업 브랜치

`refac/ts-migration`

# ☑ Refactoring TODO

- [x] 모든 js 파일 ts/tsx 파일로 변환
- [x] https://api.imhere.im/swagger-ui/index.html 스키마 타입 추가
- [x] 최소한의 타입 오류 수정
- [x] API 함수 리턴 타입 정의

**Comment by eugene028** [comment]
타입스크립트 짤 대박이네요..
